apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: selenium-appset-directories-path
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MoreiraT2/test-selenium.git
        revision: main
        directories:
          - path: app
  template:
    metadata:
      name: selenium-grid
    spec:
      project: default
      source:
        repoURL: https://github.com/MoreiraT2/test-selenium
        path: '{{ path }}'
        targetRevision: main
        helm:
          valueFiles:
            - values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: selenium
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
