apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: selenium-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MoreiraT2/test-selenium.git
        revision: main
        directories:
          - path: ./dev/values.yaml
  template:
    metadata:
      name: selenium-url-directories-path
    spec:
      project: default
      source:
        repoURL: https://www.selenium.dev/docker-selenium
        chart: selenium-grid
        targetRevision: "0.37.1"
        helm:
          valueFiles:
            - 'dev/values.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: selenium-url-directories-path
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
