apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: selenium-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/Flutter-Global/gsgkd-configrepo-aws-ppb.git
        revision: dev
        directories:
          - path: environments/dev
  template:
    metadata:
      name: selenium
    spec:
      project: default
      source:
        repoURL: "https://www.selenium.dev/docker-selenium"
        chart: selenium
        targetRevision: '0.37.0'
        helm:
          valueFiles:
            - '{{path}}/values.yml'
      destination:
        server: https://kubernetes.default.svc
        namespace: selenium-{{path.basename}}
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
