apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: selenium-appset-helm-values
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MoreiraT2/test-selenium.git
        revision: main
        files:
          - path: ./dev
  template:
    metadata:
      name: selenium-with-helm-values
    spec:
      project: default
      source:
        repoURL: https://www.selenium.dev/docker-selenium
        chart: selenium-grid
        targetRevision: "0.37.1"
        helm:
          values: |
            chromeNode:
              enabled: false
              extraEnvironmentVariables:
                - name: "SE_NODE_MAX_SESSIONS"
                  value: "2"
                - name: "SE_NODE_MAX_INSTANCES"
                  value: "1"
                - name: "SE_NODE_OVERRIDE_MAX_SESSIONS"
                  value: "true"
                - name: "SE_NODE_SESSION_TIMEOUT"
                  value: "120"
            edgeNode:
              enabled: false
            hub:
                  serviceType: "NodePort"
            ingress:
                  enabled: true
      destination:
        server: https://kubernetes.default.svc
        namespace: selenium-helm-parameters
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
