apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: selenium-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MoreiraT2/test-selenium
        revision: main
        files:
          - path: ./dev
  template:
    metadata:
      name: selenium
    spec:
      project: default
      source:
        repoURL: https://www.selenium.dev/docker-selenium
        chart: selenium-grid
        targetRevision: "0.37.0"
        helm:
          values: |
            chromeNode:
              imageName: "node-chrome"
              imageTag: "latest"
              extraEnvironmentVariables:
                - name: "SE_NODE_MAX_SESSIONS"
                  value: "1"
                - name: "SE_NODE_MAX_INSTANCES"
                  value: "1"
                - name: "SE_NODE_OVERRIDE_MAX_SESSIONS"
                  value: "true"
                - name: "SE_NODE_SESSION_TIMEOUT"
                  value: "120"
            hub:
                  serviceType: "NodePort"
            ingress:
                  enabled: true
      destination:
        server: https://kubernetes.default.svc
        namespace: selenium
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
