apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: selenium-grid-applicationset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MoreiraT2/test-selenium.git
        revision: main
        files:
          - path: 'dev/values.yaml'

  template:
    metadata:
      name: selenium
    spec:
      project: default
      source:
        repoURL: 'https://www.selenium.dev/docker-selenium'
        chart: selenium-grid
        targetRevision: '0.37.1'
        helm:
          valueFiles:
            - 'dev/values.yaml'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: selenium-url-files-path
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
