apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: selenium-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/MoreiraT2/test-selenium
        revision: main
        files:
          - path: 'dev/values.yaml'
  template:
    metadata:
      name: selenium
    spec:
      project: default
      source:
        repoURL: https://github.com/MoreiraT2/test-selenium
        chart: selenium-grid
        targetRevision: "0.37.0"
        helm:
          valueFiles:
            - dev/values.yaml
      destination:
        server: https://kubernetes.default.svc
        namespace: selenium
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
