apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: selenium-project
  namespace: argocd
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: 'selenium'
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
