global:
  chromeNode:
    imageTag: "4.0"
    extraEnvironmentVariables:
      - name: "SE_NODE_MAX_SESSIONS"
        value: "1"
      - name: "SE_NODE_MAX_INSTANCES"
        value: "1"
      - name: "SE_NODE_OVERRIDE_MAX_SESSIONS"
        value: "true"
      - name: "SE_NODE_SESSION_TIMEOUT"
        value: "120"
  hub:
    serviceType: "NodePort"
  ingress:
    enabled: true
