chromeNode:
      imageName: "node-chrome"
      imageTag: "latest"
      extraEnvironmentVariables:
        - name: "SE_NODE_MAX_SESSIONS"
          value: "1"
        - name: "SE_NODE_MAX_INSTANCES"
          value: "1"
        - name: "SE_NODE_OVERRIDE_MAX_SESSIONS"
          value: "true"
        - name: "SE_NODE_SESSION_TIMEOUT"
          value: "120"
ingress:
      enabled: true
