apiVersion: v2
appVersion: nightly
dependencies:
- condition: autoscaling.enabled, keda.enabled
  name: keda
  repository: https://kedacore.github.io/charts
  version: 2.16.0
- condition: ingress.enableWithController, ingress-nginx.enabled
  name: ingress-nginx
  repository: https://kubernetes.github.io/ingress-nginx
  version: 4.11.3
- condition: tracing.enabled, jaeger.enabled
  name: jaeger
  repository: https://jaegertracing.github.io/helm-charts
  version: 3.3.2
- condition: monitoring.enabled, prometheus-stack.enabled
  name: kube-prometheus-stack
  repository: https://prometheus-community.github.io/helm-charts
  version: 65.8.1
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
maintainers:
- email: selenium-developers@googlegroups.com
  name: SeleniumHQ
  url: https://github.com/SeleniumHQ
name: selenium-grid
sources:
- https://github.com/SeleniumHQ/docker-selenium
type: application
version: 1.0.0-nightly
